"""Add total_used_mb to DataWallet

Revision ID: 009e0832655a
Revises: 70e9e04b2f4b
Create Date: 2025-11-07 14:51:18.778960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009e0832655a'
down_revision = '70e9e04b2f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_used_mb', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_wallet', schema=None) as batch_op:
        batch_op.drop_column('total_used_mb')

    # ### end Alembic commands ###
