"""Add total_purchased_mb to DataWallet

Revision ID: 70e9e04b2f4b
Revises: 
Create Date: 2025-11-02 10:23:59.845232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e9e04b2f4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_purchased_mb', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_wallet', schema=None) as batch_op:
        batch_op.drop_column('total_purchased_mb')

    # ### end Alembic commands ###
