"""add usage tracking fields to user

Revision ID: 25f83c665709
Revises: 5ce1542ebd92
Create Date: 2025-11-14 13:15:16.651299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f83c665709'
down_revision = '5ce1542ebd92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_used_mb', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_used_mb')

    # ### end Alembic commands ###
