"""add usage tracking fields to user

Revision ID: 5ce1542ebd92
Revises: 
Create Date: 2025-11-14 13:04:46.578813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce1542ebd92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_entry', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount_mb',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('data_item', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('amount_mb',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_column('total_used_mb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_used_mb', sa.INTEGER(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('mobile',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('amount_mb',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('data_item', schema=None) as batch_op:
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('data_entry', schema=None) as batch_op:
        batch_op.alter_column('expiry_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('amount_mb',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
