"""Add total_used_mb to User for all-time usage

Revision ID: 6d89d5e85401
Revises: 009e0832655a
Create Date: 2025-11-07 16:06:24.210411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d89d5e85401'
down_revision = '009e0832655a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_used_mb', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_used_mb')

    # ### end Alembic commands ###
